
#Levenshtein distance  一条序列变成另一条序列需要经过的步骤数


import re

def LCSBackTrack(v, w):
    n = len(v)
    m = len(w)
    s = []

    for i in range(n + 1):
        s.append([])
        for j in range(m + 1):
            s[i].append(0)
    #print(s)


    for i in range(1,n+1):
        s[i][0]=s[i-1][0]-1

    #print(m)
    for j in range(1,m+1):
        s[0][j]=s[0][j-1]-1
    # print(m)
    #print(s)

    for i in range(1, n + 1):
        for j in range(1, m + 1):

            if v[i - 1] == w[j - 1]:
                s[i][j] = s[i - 1][j - 1]

            else:
                heng = s[i][j - 1] - 1
                shu = s[i - 1][j] - 1
                mismatch = s[i - 1][j - 1] -1
                s[i][j] = max(heng, shu, mismatch)


    print(abs(s[n][m]))
    #return Backtrack, n, m


#获得打分矩阵
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
V = input("what is the v string:")
W = input("what is the w string:")

LCSBackTrack(V, W)


#WANFTMTLGPQCERAYSDTDMNQIAYYPILHYWICRKRDMGADYCIRCLGPMETFRSYYCADIVYVNTAQVRCKQHRPSIQVISKNCMFKEDTWMMFFYFMTIEREFCYFSQRLDHAYILIDTWSCPDIVAVKGADCQRNSIWNIEFNVCDSSGDRHYYKGCPPERWSLRTFQRGHFPYRLKECWATSFGEVDRHKIDEFEVEPQPQVNSNRGWWYTELPNPIHARAYDWADAALVRKYDMKEFINPHGCMKYCCWVWGMTMDYLNIMKIDQKWIFNFIHALGSFPYPEPYRSFRTQIVFMRCCTQDPFESIVRTYDVKRWSDVSWYHWKWMHMACISHTWTRWWPRGCPITMDDEVLAGWKCLMMFVCSCQRHDNSVCIAHDGPPCEWNRQHASHLHAHFELMTQFRKKVVPSGSMQGWDRQNIVRAAMFTLWCHSQLMTRLFSEYEDKEFVVKAPLQLMYTTAMQGKKHWCRHKFNFFEDIADDLCYAIVTNWINMWKWSEDSRYAFRDEVIATVHAIFPHNMGFRQNVIFDEQSNKTWDVAFEHQEPKLSPSWQMCQAMNKRDRRSWKVLQRLHQQYFELNSHQTMVCLEYKSEYGADHRDWGHKRKQIWSVFVIEPMCYCECHNCWDEVVQEHWHNMFNYYWWNLMSRIGSMFMCQLRSPCNRTIDYRDMMCEPMKISSIDGCCGWEISPWENENHYWTAPENHMGVVNHDWTKKIYVISWWIMQYSQMLLKSTCGENVRHVEFKPRQWFWCCHMTPR
#WANFGMTLGRAYSDDMNQIAYYPILHYIICRKRKVWWYLFRCLGPMETFRSECNTAQAVFSYGKHRCKMEQECFHRPWGEMDTHMMGKQDITMETTIEREFCYILIDTWSCPDAPQRNSIWNICTLSSGDRHYYKGPYPERWSLFPYRLKECWATENPPNDSMGWLNDGVVEPQPQVNSCRGWWYTELPNPIHARAYMYKDWADAALVNKIDMKCDLQASIFINPVGCEKYCCWVDYLNIMKIFSHALGSFPDPEPKRDTFVYWVIVTLKNCEDYFESIVRTYDVKRWSDVSWYHWKWMHYSMRSMCIVWGCVREYKGKCDEVLAGWKCLMHKNWQVHFVCSCQRHDGPCEWNRQDASHLHAHFELMTKVVMRQNYALTWCHSQLSTVKAPLQHWCRHKFNFFATVTNWINTFNMTEWKWTDNNPRDEVIATVHAIFPWPEADSHDMAGFYQNVIFFPCELKGNWPCYQSNGTWDVAFEHQEPDRRSWKVLIHREGGLHQMTMFYQMVMATELNSTMVCLSIRSYKSEYGADHRDWGHKRKQIWSAFVIEPMCYCENIDCFLNCVDEVSQEHWHYTLECLSMFTYYKIAWPQFWNDPIMSRGSMFFCQFYRDMMCEPMKESSISFQGDKEWWISPWENDWTKKIYDISWWIRQYVHAHLLDSTVRHVPRQWWIEDPRSWCCHMTPR



